import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'));
const output = await build({ absWorkingDir: root, entryPoints: ['src/client.js'], bundle: true, write: false,
  metafile: true, format: 'cjs', platform: 'browser', target: ['chrome105'], external: ['react', '@deepseek-ai/dsh-client-ui-primitives'],
  define: { 'process.env.NODE_ENV': '"production"', __DSH_FIND_ALL_VERSION__: JSON.stringify(pkg.version) }, legalComments: 'inline' });
if (Object.keys(output.metafile.inputs).some(path => /node_modules\/react\//u.test(path))) throw new Error('React must be supplied by the Host, not bundled');
const source = '// Generated by npm run build. Edit src/, then rebuild.\n' +
  'window.__ModuleLoader__.load({id:' + JSON.stringify(pkg.name) + ',factory:(require)=>{\nvar module={exports:{}};var exports=module.exports;\n' +
  output.outputFiles[0].text + '\nreturn module.exports;\n}});\n';
const destination = resolve(root, 'lib/client.js');
if (process.argv.includes('--check')) {
  if (await readFile(destination, 'utf8') !== source) throw new Error('lib/client.js is stale; run npm run build');
  console.log('build-client: checked-in client is reproducible');
} else await writeFile(destination, source);
